[package]
name = "refix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.8.0"
memchr = "2.7.1"
memmap2 = "0.9.4"
rayon = "1.9.0"
